t=0:0.01:7;
v0=1;
R=1;
v=v0./(1+t);
s=log(1+t);
an=v0^2./(1+t).^2/R;
figure
subplot(3,1,1)
plot(t,v,'r-')
title('小球的速度曲线')
xlabel('\itt/\its')
ylabel('\itv/\it(m*s)')
subplot(3,1,2)
plot(t,s,'g-')
title('小球的路程曲线')
xlabel('\itt/\its')
ylabel('\its/\itm')
subplot(3,1,3)
plot(t,an,'b-')
title('小球的法相加速度曲线')
xlabel('\itt/\its')
ylabel('\itan/\itm*s^2')