% 下降过程中，v上升，f=kv，总a下降，无关初速度，最后v会趋近vmax
% vmax 取极限速度为单位1，
g=10;
v0=0.1:0.2:1;   % 不同初速度矩阵
t=0:0.001:7;
[V0,T]=meshgrid(v0,t);  % 确保V0,T维度相同
V=1-(1-V0).*exp(-g*T);
X=T+(1/g-V0/g).*(exp(-g*T)-1);
figure
plot(T(:,1),V(:,1),'r-',...
    T(:,2),V(:,2),'g-',...
    T(:,3),V(:,3),'b-',...
    T(:,4),V(:,4),'k-',...
    T(:,5),V(:,5),'c-');
legend(sprintf('v0=%.2f',v0(1)),...
    sprintf('v0=%.2f',v0(2)),...
    sprintf('v0=%.2f',v0(3)),...
    sprintf('v0=%.2f',v0(4)),...
    sprintf('v0=%.2f',v0(5)))
title('小球下降速度随时间变化曲线')
xlabel('\itt/\its');
ylabel('\itv/\itm*s')

figure
plot(T(:,1),X(:,1),'r-',...
    T(:,2),X(:,2),'g-',...
    T(:,3),X(:,3),'b-',...
    T(:,4),X(:,4),'k-',...
    T(:,5),X(:,5),'c-');
legend(sprintf('v0=%.2f',v0(1)),...
    sprintf('v0=%.2f',v0(2)),...
    sprintf('v0=%.2f',v0(3)),...
    sprintf('v0=%.2f',v0(4)),...
    sprintf('v0=%.2f',v0(5)))
title('小球下降距离随时间变化曲线')
xlabel('\itt/\its');
ylabel('\itx/\itm')

